require("vstudio")

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
	premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
	premake.w('<VcpkgTriplet Condition="\'$(Platform)\'==\'x64\'">x64-windows-static</VcpkgTriplet>')
	premake.w('<VcpkgEnabled>false</VcpkgEnabled>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
	local calls = base(prj)
	table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
	return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
	local calls = base(prj)
	table.insertafter(calls, vs.globals, vcpkg)
	return calls
end)

workspace "Sandbox"
	architecture "x64"
	configurations
	{
		"Debug",
		"Release"
	}
	
	startproject "GrayscaleConv"

outputdir = "%{cfg.system}-%{cfg.buildcfg}-%{cfg.architecture}"

group ""
	include "Utils"
	include "VectorAddition"
	include "MatrixMultiplication"
	include "GrayscaleConv"
	include "HistogramEqualization"
	include "NegativeImg"
	include "GaussianBlur"
	include "SobelEdgeDetection"
	include "BrightnessAdjustment"
	include "Rotate90CW"
	include "ImageThresholding"
	include "SepiaTone"
	include "BilateralFilter"
	include "CannyEdgeDetection"
	include "OilPainting"
	include "Cartoonization"
	include "Halftoning"
	include "ParticlesSim"
	include "NBodySim"
	include "BoidsSim"
group ""


